### ISSUE TITLE
Open Stella to the world

### ISSUE THREAD

**Issue by reportaman** [Shrimpram/vim-stella#12]
This profile is my favored profile, quite simply put. It would be nice to have it in a format that is parsable. I created a JSON using the Windows Terminal naming for colors. Could you have a look at the colors if they make sense, and suggest if any improvements that can be made? Also, I used same colors for bright and non-bright, not sure if you have more colors that substitute well there. It can perhaps be offered put in the repository of themes like: https://github.com/mbadolato/iTerm2-Color-Schemes, and https://github.com/Mayccoll/Gogh.

So, a few questions:

1. Do you have different Bright colors that pair well with the normal ones used below?
2. Is the selectionBackground color correct? or is there a better one?
3. Are the normal colors for black, red, green, ... white chosen below correct?

```json
{
    "name": "Stella",
    "black": "#2B213C",
    "red": "#C79987",
    "green": "#ACC79B",
    "yellow": "#C7C691",
    "blue": "#A5AAD4",
    "purple": "#C594FF",
    "cyan": "#9BC7BF",
    "white": "#B4A5C8",
    "brightBlack": "#2B213C",
    "brightRed": "#C79987",
    "brightGreen": "#ACC79B",
    "brightYellow": "#C7C691",
    "brightBlue": "#A5AAD4",
    "brightPurple": "#C594FF",
    "brightCyan": "#9BC7BF",
    "brightWhite": "#B4A5C8",
    "foreground": "#B4A5C8",
    "background": "#2B213C",
    "cursorColor": "#B4A5C8",
    "selectionBackground": "#655978"
}
```

**Comment by Shrimpram** [comment]
I've been thinking of having something similar, creating different repos for different formats of the scheme, e.g. for (n)vim, [kitty](https://github.com/kovidgoyal/kitty) but I've been caught up in school related stuff for a while and will probably only have time to start this next week. As far as your questions go:

1. I'm in the process of making a bright scheme, but I've found that the current color definitions for colors are a bit tricky to cleanly make a light/dark scheme combination so I will probably need to tweak them a bit. This is still a WIP though.
2. The selection background should correspond to the "VISUAL" color in [stella.erb](https://github.com/Shrimpram/vim-stella/blob/e1279c1d6516ed7edc6ccb58c4bf382861e5a6b0/colors/stella.erb#L151)
3. The other definitions look good.

I'm leaving this open for now, once I've set up something that should enable easy organization of new schemes I'll link it here and close the issue. This will also require defining some new colors since the current definition doesn't include some colors that other apps use, e.g. there is no definition for shades such as brightRed/Green/etc.

**Comment by shreerammodi** [comment]
Sorry for the update taking so long, but I've revamped the scheme to include dark + light mode as well as included a definition of the scheme and templates using [mustache](https://mustache.github.io/) so that schemes for other programs can be easily made. The new repo is over at [shrimpram/stella](https://github.com/shrimpram/stella).
