### ISSUE TITLE
Good work -- keep it up

### ISSUE THREAD

**Issue by reportaman** [Shrimpram/vim-stella#6]
👍

**Comment by Shrimpram** [comment]
Thank you! If I may ask, how did you find this repo? I haven't really posted it anywhere other than my PRs to romainl's repo and the base16 repo.

**Comment by reportaman** [comment]
@Shrimpram It probably showed up in my feed to the right side of the page, though am not fully sure. Anyway, I am happy to have come across it. Am very picky in my color scheme choices, so you have indeed achieved a feat :) Is there a [airline-theme](https://github.com/vim-airline/vim-airline-themes) that you intend to add?

**Comment by Shrimpram** [comment]
@reportaman I see, glad to have you here though :).

> airline-theme

I'm an nvim user, and I personally use [hardline](https://github.com/ojroques/nvim-hardline). I have [my own fork](https://github.com/Shrimpram/nvim-hardline) with this theme loaded, I haven't added it to this repo yet since it's still a WIP and I need to tweak some of the settings. PR's are more than welcome though if you have any free time to port this scheme to airline!

Another note in case you decide to port it, I might change some of the colors around a bit; this scheme is still pre-release and I wanted to add more color variance. The main problem I have with the current palette is that a lot of the hues seem the same. For example, when I use the scheme for viewing git diffs it becomes very difficult to tell the difference between added and deleted and changed lines. I am working on the newer scheme in the [newscheme branch](https://github.com/Shrimpram/vim-stella/tree/newscheme), below is a screenshot. Let me know if you have any thoughts, cheers!


![image](https://user-images.githubusercontent.com/67710369/120425896-e64cda00-c323-11eb-8115-06c2bc87f5b3.png)
